ogrenci=["Sedat","Deniz","Sude","Tolga","Mehmet","Berfin"]
print(ogrenci[-2])
print(ogrenci[2:5])
print(ogrenci[:3])
ogrenci[0]="Murat"
print(ogrenci)
ogrenci[1:3]=["Fatih","Sultan","Salih"]
print(ogrenci)
ogrenci.append("Kasım")
print(ogrenci)
ogrenci.insert(1,"Ahmet")
print(ogrenci)
ogrenci.remove("Murat")
print(ogrenci)
ogrenci.pop()
print(ogrenci)
ogrenci.pop(1)
print(ogrenci)
del ogrenci[0]
print(ogrenci.pop(1))
print(ogrenci)
ogrenci.sort()
print(ogrenci)
ogrenci.sort(reverse=True)
print(ogrenci)
sayi=[1,2,3]
sayi2=[4,5,6]
birles=sayi+sayi2
print(birles)
sayi.extend(sayi2)
print(sayi)